# YAML
DIR:
  DATA: '/media/wsubuntu/SSD_Data/DataPath'
  EXPERIMENT: '/media/wsubuntu/SSD_Data/vaesae_experiments/CIFAR'
DATA:
  IDENTIFIER: 'CIFAR10'
  INPUT_INITIAL_RESIZE: None
  LOAD_TR_AS_TEST: True
EXPERIMENT:
  SAVE_MODEL_AT: 20
  BATCH_SIZE: 32
MODEL:
  MODEL_CLASS: conv_ae
  MODEL_NAME: conv_ae_simple
  DATA_KEY: image
  INPUT_SIZE: 32
  INPUT_CHANNEL_SIZE: 3
  WEIGHT_DECAY: 0.0
  LEARNING_RATE: 0.0001
  RECONSTRUCTION_ERROR_FUNCTION: 'MSE'
  RECONSTRUCTION_ERROR_REDUCTION: 'mean'
  SPARSITY_ERROR: 'kl_divergence'
  SPARSITY_WEIGHT: 0.001
  SPARSITY_REDUCTION: 'sum'
  KL_DIV_RHO: 0.0001
  KL_SIGMOID: True
  KL_LOGSOFTMAX: True
  KL_MEAN: False
  BOTTLENECK_ACT_APPLY: True
  BOTTLENECK_KMEANS_APPLY: True
  BOTTLENECK_FIG_NAME_BASE: 'btl_XXX.png'
  OUTPUTS:
    PLOT_VARIANCE: False
    PLOT_HISTOGRAM: False
  LAYERS:
    encoder:
      l01_conv:   'type: Conv2d,in_channels : 3, out_channels : 32, kernel_size : 5'
      l01_act:    'type: ReLu'
      l02_maxp:   'type: MaxPool2d,kernel_size:2'
      l03_conv:   'type: Conv2d,in_channels :32, out_channels : 32, kernel_size : 5'
      l03_act:    'type: ReLu'
      flat:       'type: Flatten'
      l04_linear: 'type: Linear,in_features:3200, out_features:256'
      l04_act:    'type: ReLu'
      l05_linear: 'type: Linear,in_features:256, out_features:64'
      l05_act:    'type: ReLu'
    decoder:
      l05_linear_b: 'type: Linear,in_features:64, out_features:256'
      l05_act_b:    'type: ReLu'
      l04_linear_b: 'type: Linear,in_features:256, out_features:3200'
      l04_act_b:    'type: ReLu'
      flat_b:       'type: Unflatten'
      l03_deconv:   'type: ConvTranspose2d,in_channels :32, out_channels : 32, kernel_size : 5'
      l03_act_b:    'type: ReLu'
      l02_upsm:     'type: Upsample,scale_factor:2'
      l01_deconv:   'type: ConvTranspose2d,in_channels :32, out_channels : 3, kernel_size : 5'
      l01_act_b:    'type: ReLu'


