# YAML
DIR:
  DATA: '/home/doga/DataFolder/' # '/mnt/SSD_Data/DataPath'
  EXPERIMENT: '/home/doga/DataFolder/vaesae_experiments_cor' # '/mnt/SSD_Data/vaesae_experiments_cor' # '/mnt/USB_HDD_1TB/GitHub/keyhandshapediscovery/experiments_cor'
DATA:
  IDENTIFIER: 'MNIST'
  INPUT_INITIAL_RESIZE: None
  LOAD_TR_AS_TEST: False
  FLATTEN: True
EXPERIMENT:
  ID: 501 # just to see also in the file
  EXPLANATION: 'No vae as in 500'
  SAVE_MODEL_AT: 20
  BATCH_SIZE: 32
MODEL:
  MODEL_CLASS: linear_vae
  MODEL_NAME: linear_vae_MNIST
  DATA_KEY: image
  INPUT_SIZE: 28
  INPUT_CHANNEL_SIZE: 1
  WEIGHT_DECAY: 0.01
  LEARNING_RATE: 0.001 #
  RECONSTRUCTION_ERROR_FUNCTION: 'BCE'
  RECONSTRUCTION_ERROR_REDUCTION: 'mean'
  SPARSE_PARAMS:
    ERROR_FUNC: 'kl_divergence' # SPARSITY
    WEIGHT: 0.001
    REDUCTION: 'sum'
    APPLY_AFTER_EPOCH: 5
    KL_DIV_PARAMS:
      RHO_VALUE: 0.0001
      RHO_ONE_MODE: False
      RHO_ONE_MODE_PERC: None
      APPLY_SIGMOID: True
      APPLY_LOGSOFTMAX: True
      APPLY_MEAN: False
  BOTTLENECK:
    CHECK_ACTIVATION: True
    RUN_KMEANS: True
    FIG_NAME_BASE: 'btl_XXX.png'
  OUTPUTS:
    plot_variance: False
    plot_histogram: False
  LAYERS:
    encoder:
      l01_linear: 'type: Linear,in_features:784, out_features:512'
      l01_act:    'type: ReLu'
      l02_linear: 'type: Linear,in_features:512, out_features:512'
      l02_act:    'type: ReLu'
      l03_linear: 'type: Linear,in_features:512, out_features:1024'
      l03_act:    'type: ReLu'
      l04_linear: 'type: Linear,in_features:1024, out_features:32'
    decoder:
      l04_linear_b: 'type: Linear,in_features:32, out_features:1024'
      l03_act_b:    'type: ReLu'
      l03_linear_b: 'type: Linear,in_features:1024, out_features:512'
      l02_act_b:    'type: ReLu'
      l02_linear_b: 'type: Linear,in_features:512, out_features:512'
      l01_act_b:    'type: ReLu'
      l01_linear_b: 'type: Linear,in_features:512, out_features:784'
      l00_act_b:    'type: Sigmoid'
